yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler403 = settings.CSRF_FAILURE_VIEW
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.page_internal_server_error'


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True, verbose_name='Ссылка на группу')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментраия',
        help_text='Введите текст комментраия'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = (models.UniqueConstraint(
            fields=('user', 'author'), name='unique appversion'
        ))

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page

from .models import Follow, Post, Group, User
from .forms import PostForm, CommentForm
from .utils import add_paginator_on_page


@cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('group')
    page_obj = add_paginator_on_page(post_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = add_paginator_on_page(post_list, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    post_count = post_list.count()
    page_obj = add_paginator_on_page(post_list, request)
    if (request.user.is_authenticated
       and request.user.follower.filter(author=author).exists()):
        following = True
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'post_count': post_count,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    post_count = author.posts.all().count()
    comments = post.comments.all()
    context = {
        'form': CommentForm(),
        'post': post,
        'post_count': post_count,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=post.author.username)

        return render(request, 'posts/create_post.html', {'form': form})

    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    if request.user != author:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = add_paginator_on_page(posts_list, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(
        user=request.user, author=author).exists()
    if request.user != author and following is not True:
        Follow(user=request.user, author=author).save()
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(author=author, user=request.user).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title_name %}
    Новый пост
  {% endblock %}
  {% block content %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              {% if is_edit %}
                Редактировать запись
              {% else %}
                Добавить запись
              {% endif %}             
            </div>
            <div class="card-body">
            {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}    
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}          
                        <span class="required text-danger" >*</span> 
                      {% endif %}                 
                    </label>
                      {{ field|addclass:'form-control' }}
                      {{ field.text }}                  
                      {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                  </div>
                {% endfor %}          
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}  
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title_name %}
    Последние посты подписок
  {% endblock %}
    {% block content %}
    <div class="container">
    {% include 'includes/switcher.html' %}
      <h1>
        Последние посты подписок
      </h1>
    {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            </p>
          </article>
          {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
    {% endblock %}  

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
  {% block title_name %}
    {{ group.title }}
  {% endblock %}
    {% block content %}
    <div class="container">
      <h1>
        {{ group.title }}
      </h1>
      <p>
        {{ group.description }}
      </p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
      </article>
      <p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </p>   
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
  {% endblock %}  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title_name %}
    Последние обновления на сайте
  {% endblock %}
    {% block content %}
    <div class="container">
      {% include 'includes/switcher.html' %}
      <h1>
        Последние обновления на сайте
      </h1>
    {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>    
            {% if post.group %}   
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            <p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            </p>
          </article>
          {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </div>
    {% include 'includes/paginator.html' %}
    {% endblock %}  

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title_name %}
    Пост {{ post.text|slice:":30" }}
  {% endblock %}
  {% block content %}
  <div class="container">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if user == post.author %}
          <p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать пост</a>
          </p>
        {% endif %}
        {% load user_filters %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
          {% endfor %} 
      </article>

    </div>
  </div>
  {% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title_name %}
    Профайл пользователя {{ author.get_full_name }}
  {% endblock %}
  {% block content %}
    <div class="container">        
      <h1>Все посты пользователя {{ author.get_full_name }} </h1>
      <h3>Всего постов: {{ post_count }} </h3>
      {% if user.is_authenticated %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
      {% for post in page_obj %} 
      <article>
        <ul>
          <li>
            Автор: {{ author.get_full_name }}
            <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.created|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>       
        {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}   
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}    
    {% include 'includes/paginator.html' %}
    </div>
  {% endblock %} 
   